version: '3'

services:
# Cache chiquitita = cachitos 
  cachitos:
    image: bitnami/redis:latest
    container_name: cachitos
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

# postgres minimi con contraseña suprema
  pgminimi:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgrevieja
      POSTGRES_PASSWORD: postgrevieja
      POSTGRES_DB: minimi
    