version: '3'

services:
# Cache chiquitita = cachitos 
  cachitos:
    image: bitnami/redis:latest
    container_name: cachitos
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

# postgres minimi con contraseña suprema
  pgminimi:
    image: dtbse.dockerfile
    container_name: pgminimi
    volumes:
      - pgminimi:/var/lib/postgresql/data